spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            testing:
            - uri: 'https://appchatservice.shared-testing.audibene.net'
              metadata:
                management.context-path: '/.well-known'
                user.name: 'user'
                user.password: 'password'
            staging:
            - uri: 'https://appchatservice.shared-staging.audibene.net'
              metadata:
                management.context-path: '/.well-known'
                user.name: 'user'
                user.password: 'password'
server:
  port: 8082
